pipeline {
    agent {
        label 'agent-11'
    }

    options {
        timeout(time:15, unit:'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    stages {
        stage('init') {
            steps {
                sh '''
                    cd expense-terraform
                    cd expense-terraform-dev
                    cd 01-vpc
                    terraform init -reconfigure
                '''
            }
        }
        stage('plan') {
            steps {
                sh '''
                    echo plan stage
                '''
            }
        }
        stage('deploy') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps {
                sh '''
                    echo deploy stage
                '''
            }
        }
    }

    post {
        success {
            echo 'will run if success'
        }
        always {
            echo 'will run always'
            deleteDir()
        }
        failure {
            echo 'will run if failed'
        }
    }
}