pipeline {
    agent {
        label 'agent-1'
    }

    options {
        timeout(time: '15' , unit:'MINUTES' )
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    environment {

    }

    parameters {
        
    }

    stages {
        stage('init') {
            steps {
                sh "
                "
            }
        }

        stage('plan') {
            steps {
                sh "
                "
            }
        }
    }

    post {
        always {

        }
        success {

        }
        failure {

        }
    }
}